### ISSUE TITLE
Refactor README file

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#15]
- [ ] Need to refactor README file, need to make more readable

**Comment by nik849** [comment]
As I work through the other things, I can update this as I go

**Comment by MichaelYusko** [comment]
@nik849 it's would nice! thanks!

**Comment by MichaelYusko** [comment]
<img width="247" alt="screenshot 2017-06-26 14 07 18" src="https://user-images.githubusercontent.com/13191999/27537443-957c7a0e-5a7c-11e7-9a4c-4fdf21f8df84.png">

**Comment by MichaelYusko** [comment]
![image](https://user-images.githubusercontent.com/13191999/27537700-a042c802-5a7d-11e7-8c24-e05052d23f89.jpg)

**Comment by MichaelYusko** [comment]
<img width="255" alt="screenshot 2017-07-02 23 27 43" src="https://user-images.githubusercontent.com/13191999/27773315-866fe34a-5f7f-11e7-92d8-d9c56237e0f3.png">
<img width="646" alt="screenshot 2017-07-02 23 28 27" src="https://user-images.githubusercontent.com/13191999/27773316-88fb5fa4-5f7f-11e7-9d16-4208d6091470.png">

**Comment by MichaelYusko** [comment]
![image](https://user-images.githubusercontent.com/13191999/27773370-d1e1fb14-5f80-11e7-8f95-1c9c88bab37d.jpg)
![image 1](https://user-images.githubusercontent.com/13191999/27773371-d318538e-5f80-11e7-9ba3-04bec11f50c3.jpg)

**Comment by MichaelYusko** [comment]
<img width="211" alt="screenshot 2017-07-02 23 53 11" src="https://user-images.githubusercontent.com/13191999/27773421-fb2525e0-5f81-11e7-9854-384effdf9ce4.png">
<img width="279" alt="screenshot 2017-07-02 23 54 33" src="https://user-images.githubusercontent.com/13191999/27773423-fc0e8604-5f81-11e7-8690-25a66ee87511.png">
