### ISSUE TITLE
Add news support

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#17]
- [ ] Add to Chucky news support

**Comment by sk364** [comment]
Any news APIs you have in mind ?

**Comment by MichaelYusko** [comment]
@sk364 https://newsapi.org/bbc-news-api

**Comment by sk364** [comment]
Are you implementing this?

**Comment by MichaelYusko** [comment]
@sk364 no, for now I'm working on this https://github.com/MichaelYusko/Bot-Chucky/blob/master/bot_chucky/helpers.py#L205

**Comment by Samy-33** [comment]
Is anyone working on this feature? Becuase I am implementing it.

**Comment by MichaelYusko** [comment]
@Samy-33 Hi, no.

**Comment by MichaelYusko** [comment]
@Samy-33 And if you will implement the support for new, it's would be cool.

**Comment by Samy-33** [comment]
@MichaelYusko , that sounds good to me. :)

**Comment by MichaelYusko** [comment]
@Samy-33 Thanks, for the PR, also if you will have a free time, could you attach pictures? to the README file? it's would be cool, also add your into `CONTRIBUTORS.md` file;)

**Comment by Samy-33** [comment]
@MichaelYusko Ok, I will. :)

**Comment by Samy-33** [comment]
Images to be added to README.md  
![1](https://user-images.githubusercontent.com/15676805/27868476-6ab124b0-61ba-11e7-9f3e-a925e9ec6671.jpg)
![2](https://user-images.githubusercontent.com/15676805/27868483-6f273336-61ba-11e7-8cc5-4173709a50ab.jpg)

**Comment by MichaelYusko** [comment]
@Samy-33 You also could to check the repo
https://github.com/The-PyWaiters/GiphyPy

**Comment by Samy-33** [comment]
@MichaelYusko I checked out that repository already. I am wondering what else might be added to that project.

**Comment by MichaelYusko** [comment]
@Samy-33 you able to add endpoints which not enough, or refactor;)
