### ISSUE TITLE
Add feature tweet

### ISSUE THREAD

**Issue by sk364** [MichaelYusko/Bot-Chucky#23]

**Comment by MichaelYusko** [comment]
@sk364 What do you mean, `tweet`? I assume you mean twitter:)?

**Comment by sk364** [comment]
I meant, twitter only. You tweet there. So, a feature to be able to 'tweet' on 'twitter', I meant.

**Comment by MichaelYusko** [comment]
It's would be cool! could you implement this feature? of course when you will have a free time:)

**Comment by sk364** [comment]
Sure. I will !

**Comment by MichaelYusko** [comment]
@sk364 Nice! thanks

**Comment by MichaelYusko** [comment]
@sk364 When I'll finish integrate  `StackExchange` API, and you will finish `tweet`, I'll create a new version and upload on PyPi👍

**Comment by sk364** [comment]
What are your ideas on implementation of sending tweets ?

**Comment by MichaelYusko** [comment]
@sk364 In any case we need to use Twitter API, and feel free implement your ideas;) I'll review your a PR.
