### ISSUE TITLE
How to get access token for Facebook?

### ISSUE THREAD

**Issue by sk364** [MichaelYusko/Bot-Chucky#24]

**Comment by sk364** [comment]
Got it.

**Comment by sk364** [comment]
You should provide docs, btw.

**Comment by MichaelYusko** [comment]
Yes, I'll add it.

**Comment by sk364** [comment]
What should be the sender id to send messages to?

**Comment by MichaelYusko** [comment]
@sk364 `sender_id` it's who wrote to the bot. in order to test bot, you need to create Facebook page.
https://developers.facebook.com/ here you able to create an app

**Comment by sk364** [comment]
{"error":{"message":"(#100) Parameter error: You cannot send messages to this id","type":"OAuthException","code":100,"fbtrace_id":"F9zpiUASttQ"}}

I put `sender_id` as my profile's id.

**Comment by sk364** [comment]
Help me in getting `sender_id`.

**Comment by MichaelYusko** [comment]
@sk364  you created Facebook app?

**Comment by sk364** [comment]
Yes.

**Comment by MichaelYusko** [comment]
Okay, installed ngrok?

**Comment by sk364** [comment]
Yes.

**Comment by MichaelYusko** [comment]
or you can read [the Tutorial](http://masnun.com/2016/05/22/building-a-facebook-messenger-bot-with-python.html), and you will understand how it works;)

**Comment by MichaelYusko** [comment]
because I little bit confused, about which `sender_id` you talking, or you can make a PR

**Comment by sk364** [comment]
{"error":{"message":"(#100) Parameter error: You cannot send messages to this id","type":"OAuthException","code":100,"fbtrace_id":"GLtHlhYaQTN"}}
Getting this error.

**Comment by sk364** [comment]
I got where I can get `sender_id` from. Thanks! ngrok helped.

**Comment by MichaelYusko** [comment]
just check Flask example in the README file.
