### ISSUE TITLE
Add Instagram support

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#27]

**Comment by sk364** [comment]
I will work on this.

**Comment by MichaelYusko** [comment]
@sk364 Nice! also check the PR https://github.com/MichaelYusko/Bot-Chucky/pull/25 You need to fix tests.

**Comment by sk364** [comment]
@MichaelYusko  There is no endpoint for posting media on Instagram.
https://www.instagram.com/developer/endpoints/
