### ISSUE TITLE
Add SoundCloud support

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#32]
- [ ] User able to search information about track,also bot must provide some information about track to the user messenger
[SoundCloud API](https://developers.soundcloud.com/docs/api/guide)

**Comment by nik849** [comment]
@MichaelYusko I'll work on this

**Comment by MichaelYusko** [comment]
@nik849 Cool! thanks 👍

**Comment by nik849** [comment]
@MichaelYusko, what sort of functionality are you looking for?

**Comment by MichaelYusko** [comment]
@nik849 I think we can start with the [search endpoint](https://developers.soundcloud.com/docs/api/guide#search) bot will be return some information about track/singer to a user messenger, what do you think?

for example: `bot.send_soundcloud_message(singer='Kings of Leon')` and bot will be return some information about `Kings of Leon`, and the same for tracks and etc.

**Comment by nik849** [comment]
@MichaelYusko ok great, I've added in already functions to get track information from a url, i'll add this in too and make a PR when done

**Comment by MichaelYusko** [comment]
@nik849 Sure, please do it when you have a free time;)

**notice**: bot must communicate via messenger
