### ISSUE TITLE
Bot messenger add pictures to the weather message

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#38]
If bot replied for example: Current weather in New-York is: cloudy sky, also need to  attach picture, something like this: https://image.freepik.com/free-vector/coloured-weather-icons-collection_1126-30.jpg

**Comment by nik849** [comment]
While waiting for the Soundcloud token, do you mind if I do this?

**Comment by MichaelYusko** [comment]
@nik849 Sure, no problem!
