### ISSUE TITLE
Add Gmail support

### ISSUE THREAD

**Issue by sk364** [MichaelYusko/Bot-Chucky#41]

**Comment by MichaelYusko** [comment]
@sk364 how do you implement it?  and what exactly we will do?

**Comment by sk364** [comment]
Bot can send mails.
Use case : bot_chucky.send_mail(to='abc@xy.com', subject='test test', body='Some creative content here')

**Comment by sk364** [comment]
Another use case : bot_chucky.get_mails(unread=True)

**Comment by sk364** [comment]
> how do you implement it?

Using python gmail api. https://developers.google.com/gmail/api/guides/sending

**Comment by MichaelYusko** [comment]
@sk364 Yes, it's cool idea!
one notice: one notice: Bot need to communicate with a user via messenger of facebook

**Comment by sk364** [comment]
On messenger, the user can type "Send mail, To : abc@xyz.com, Subject : any subject, Body : text in the body".
That's just a sample... we can decide the messenger text body and the bot can parse the text easily and do the processing and send mails and return back success messages to the user and/or the link to the mail.
P.S. : We can take care of attachments later.

**Comment by MichaelYusko** [comment]
@sk364 Yes, approve. It's what we looking 👍

**Comment by MichaelYusko** [comment]
@sk364 merged your branch, also would be cool if you will add documentation how to use Gmail.
