### ISSUE TITLE
Gmail, crashed flask server

### ISSUE THREAD

**Issue by MichaelYusko** [MichaelYusko/Bot-Chucky#54]
@sk364 need to fix it
first - https://github.com/MichaelYusko/Bot-Chucky/blob/master/bot_chucky/helpers.py#L14
When a Flask server started
`ImportError: cannot import name 'discovery'`, also update `requirements.txt` file.

second - https://github.com/MichaelYusko/Bot-Chucky/blob/master/bot_chucky/helpers.py#L171
if a User has not created `.credentials` directory and `gmail-python-quickstart.json` file, A Flask server can't run.

Need to fix it.

**Comment by MichaelYusko** [comment]
@sk364 See please,
I fixed - https://github.com/MichaelYusko/Bot-Chucky/commit/fa44c6d998bc7841b630cdf0ddcb8fded5602422#diff-d689926df6cdd27afc36bdf05b6e842eR13
 Now server start correctly

**Comment by sk364** [comment]
Works fine. I made a few changes of my own. I will create a PR for it.
