### ISSUE TITLE
Adding support of dictionary

### ISSUE THREAD

**Issue by Samy-33** [MichaelYusko/Bot-Chucky#95]
I am planning to add dictionary feature, which searches for the definitions of a word given.  
I will be using web scraping as the the api's I have found so far are costly and wouldn't be very good for the Bot-Chucky.  
@MichaelYusko What do you suggest?

**Comment by MichaelYusko** [comment]
@Samy-33 agree

**Comment by Samy-33** [comment]
Pictures for README  
![img_0786](https://user-images.githubusercontent.com/15676805/28264397-6511fd84-6b08-11e7-95f7-068049c0c61f.PNG)
![img_0787](https://user-images.githubusercontent.com/15676805/28264398-657e9b7e-6b08-11e7-8328-9d1a6b23dcca.PNG)
